name: CD pipline

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull docker image
        run: sudo docker pull evify/frontend_logistic:latest
      - name: Delete old docker container
        run: sudo docker rm -f frontend_container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 80:3000 --name frontend_container  evify/frontend_logistic